  
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphe.values;

import java.io.IOException;
//import com.formdev.flatlaf.FlatDarkLaf;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;

import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author matis
 */
public class GUI extends javax.swing.JFrame {
    private Graphe graphe;
    private String fileName;
    public boolean opened;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.fileName = null;
        this.opened = false;
    }
    public String getFileName(){
        return this.fileName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jToolBar1 = new javax.swing.JToolBar();
        toolBarPan = new javax.swing.JPanel();
        lbl_affichage = new javax.swing.JLabel();
        cb_ville = new javax.swing.JCheckBox();
        cb_restaurant = new javax.swing.JCheckBox();
        cb_loisirs = new javax.swing.JCheckBox();
        cb_autoroute = new javax.swing.JCheckBox();
        cb_nationale = new javax.swing.JCheckBox();
        cb_departementale = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Canvas = new GrapheDraw();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jFileChooser1.setCurrentDirectory(new java.io.File(".\\inputFiles"));
        jFileChooser1.setDialogTitle("Choisissez un fichier dde Graphe");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("TXT File","txt"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jFileChooser1ActionPerformed(evt);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
        //this.setResizable(false);
        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        jToolBar1.setRollover(true);

        lbl_affichage.setText("Affichage :");

        cb_ville.setSelected(true);
        cb_ville.setText("Villes");
        cb_ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_villeActionPerformed(evt);
            }
        });

        cb_restaurant.setSelected(true);
        cb_restaurant.setText("Restaurants");
        cb_restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_restaurantActionPerformed(evt);
            }
        });

        cb_loisirs.setSelected(true);
        cb_loisirs.setText("Loisirs");
        cb_loisirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loisirsActionPerformed(evt);
            }
        });


        jLabel1.setText("Liens :");

        cb_autoroute.setSelected(false);
        cb_autoroute.setText("Autoroutes");
        cb_autoroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_autorouteActionPerformed(evt);
            }
        });

        cb_nationale.setSelected(false);
        cb_nationale.setText("Nationales");
        cb_nationale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nationaleActionPerformed(evt);
            }
        });

        cb_departementale.setSelected(true);
        cb_departementale.setText("Departementales");
        cb_departementale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_departementaleActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout toolBarPanLayout = new javax.swing.GroupLayout(toolBarPan);
        toolBarPan.setLayout(toolBarPanLayout);
        toolBarPanLayout.setHorizontalGroup(
            toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_loisirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_restaurant, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(cb_ville, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_affichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(toolBarPanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                .addContainerGap())
                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(cb_autoroute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_nationale, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(cb_departementale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        toolBarPanLayout.setVerticalGroup(
            toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_affichage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_ville)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_restaurant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_loisirs)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addComponent(lbl_affichage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_autoroute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nationale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_departementale)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        jToolBar1.add(toolBarPan);

        javax.swing.GroupLayout CanvasLayout = new javax.swing.GroupLayout(Canvas);
        Canvas.setLayout(CanvasLayout);
        CanvasLayout.setHorizontalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        CanvasLayout.setVerticalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Fichier");

        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Ouvrir");
        openFile.setToolTipText("");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu1.add(openFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_jFileChooser1ActionPerformed
        this.fileName = jFileChooser1.getSelectedFile().getAbsolutePath();
        //System.out.println(fileName);
        this.opened = true;
        GrapheApp.initApp();
        System.out.print("oui");
        jFrame1.dispose();
        // graphe = GrapheApp.getGraphe();
        // Canvas.drawGraph(graphe);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        // graphe = GrapheApp.getGraphe();
        // try{
        //     System.out.print(graphe.getNoeuds().size() * 2 * 10);
        //     if((graphe.getNoeuds().size() * 2 * 10 < GUI.getCanvas().getWidth()) && (graphe.getNoeuds().size() * 2 * 10 < GUI.getCanvas().getHeight())){
        //         Canvas.clear();
        //         Canvas.changePos();
        //         Canvas.repaint();
        //     }
        // } catch(NullPointerException e){
        //     System.out.println("Pas de graphe");
        // }
        Canvas.clear();
        try{
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
            Canvas.changePos();
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
        
        Canvas.repaint();

    }//GEN-LAST:event_formComponentResized

    private void cb_villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_villeActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_villeActionPerformed

    private void cb_restaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_restaurantActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_restaurantActionPerformed

    private void cb_loisirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loisirsActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_loisirsActionPerformed

    private void cb_autorouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_autorouteActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_autorouteActionPerformed

    private void cb_nationaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nationalesActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_nationalesActionPerformed

    private void cb_departementaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_departementaleActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_departementaleActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {
        jFrame1.pack();
        jFrame1.setVisible(true);
    }
    //getter cb
    public static JCheckBox getCb_ville() {
        return cb_ville;
    }

    public static JCheckBox getCb_restaurant() {
        return cb_restaurant;
    }

    public static JCheckBox getCb_autoroute() {
        return cb_autoroute;
    }

    public static JCheckBox getCb_nationale() {
        return cb_nationale;
    }

    public static JCheckBox getCb_departementale() {
        return cb_departementale;
    }

    public static JCheckBox getCb_loisirs() {
        return cb_loisirs;
    }

    public static GrapheDraw getCanvas() {
        return Canvas;
    }

    //check for mouse motion and mouse click events


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static GrapheDraw Canvas;
    private static javax.swing.JCheckBox cb_loisirs;
    private static javax.swing.JCheckBox cb_restaurant;
    private static javax.swing.JCheckBox cb_ville;
    private static javax.swing.JCheckBox cb_departementale;
    private static javax.swing.JCheckBox cb_nationale;
    private static javax.swing.JCheckBox cb_autoroute;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_affichage;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JPanel toolBarPan;
    // End of variables declaration//GEN-END:variables
}
