  
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphe.values;

import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JToolBar.Separator;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author matis
 */
public class GUI extends javax.swing.JFrame {
    private Graphe graphe;
    private String fileName;
    public boolean opened;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.fileName = null;
        this.opened = false;
    }
    public String getFileName(){
        return this.fileName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setMinimumSize(new Dimension(1400, 850));
        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jToolBar1 = new javax.swing.JToolBar();
        toolBarPan = new javax.swing.JPanel();
        lbl_affichage = new javax.swing.JLabel();
        nbVille = new javax.swing.JLabel();
        nbRestaurant = new javax.swing.JLabel();
        nbLoisir = new javax.swing.JLabel();
        nbDepartementale = new javax.swing.JLabel();
        nbNationale = new javax.swing.JLabel();
        nbAutoroute = new javax.swing.JLabel();
        cb_ville = new javax.swing.JCheckBox();
        cb_restaurant = new javax.swing.JCheckBox();
        cb_loisirs = new javax.swing.JCheckBox();
        cb_autoroute = new javax.swing.JCheckBox();
        cb_nationale = new javax.swing.JCheckBox();
        cb_departementale = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Canvas = new GrapheDraw();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        this.addMouseListener(new clickNode());
        this.addMouseMotionListener(new clickNode());
        jFileChooser1.setCurrentDirectory(new java.io.File(".\\inputFiles"));
        jFileChooser1.setDialogTitle("Choisissez un fichier dde Graphe");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("TXT File","txt"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jFileChooser1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        //this.setResizable(false);
        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        jToolBar1.setRollover(true);

        lbl_affichage.setText("Noeuds :");

        cb_ville.setSelected(true);
        cb_ville.setText("Villes");
        cb_ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_villeActionPerformed(evt);
            }
        });

        cb_restaurant.setSelected(true);
        cb_restaurant.setText("Restaurants");
        cb_restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_restaurantActionPerformed(evt);
            }
        });

        cb_loisirs.setSelected(true);
        cb_loisirs.setText("Loisirs");
        cb_loisirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_loisirsActionPerformed(evt);
            }
        });


        jLabel1.setText("Liens :");

        cb_autoroute.setSelected(false);
        cb_autoroute.setText("Autoroutes");
        cb_autoroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_autorouteActionPerformed(evt);
            }
        });

        cb_nationale.setSelected(false);
        cb_nationale.setText("Nationales");
        cb_nationale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nationaleActionPerformed(evt);
            }
        });

        cb_departementale.setSelected(true);
        cb_departementale.setText("Departementales");
        cb_departementale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_departementaleActionPerformed(evt);
            }
        });

        nbVille.setText("Nombre : 0");
        nbRestaurant.setText("Nombre : 0");
        nbLoisir.setText("Nombre : 0");
        nbAutoroute.setText("Nombre : 0");
        nbNationale.setText("Nombre : 0");
        nbDepartementale.setText("Nombre : 0");

        javax.swing.GroupLayout toolBarPanLayout = new javax.swing.GroupLayout(toolBarPan);
        toolBarPan.setLayout(toolBarPanLayout);
        toolBarPanLayout.setHorizontalGroup(
            toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_loisirs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_restaurant, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(cb_ville, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_affichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbVille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbRestaurant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbLoisir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbDepartementale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbAutoroute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbNationale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(toolBarPanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                .addContainerGap())
                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(cb_autoroute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_nationale, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(cb_departementale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        toolBarPanLayout.setVerticalGroup(
            toolBarPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarPanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_affichage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_ville)
                .addComponent(nbVille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_restaurant)
                .addComponent(nbRestaurant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_loisirs)
                .addComponent(nbLoisir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addComponent(lbl_affichage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_autoroute)
                .addComponent(nbAutoroute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_nationale)
                .addComponent(nbNationale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_departementale)
                .addComponent(nbDepartementale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addContainerGap(421, Short.MAX_VALUE))
                
        );

        jToolBar1.add(toolBarPan);

        javax.swing.GroupLayout CanvasLayout = new javax.swing.GroupLayout(Canvas);
        Canvas.setLayout(CanvasLayout);
        CanvasLayout.setHorizontalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        CanvasLayout.setVerticalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Fichier");
        openFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFile.setText("Ouvrir");
        openFile.setToolTipText("");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jMenu1.add(openFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_jFileChooser1ActionPerformed
        this.fileName = jFileChooser1.getSelectedFile().getAbsolutePath();
        this.opened = true;
        GrapheApp.initApp();
        setNombres();
        jFrame1.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        Canvas.clear();
        try{
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
            Canvas.changePos();
            Canvas.repaint();
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }

    }//GEN-LAST:event_formComponentResized

    private void cb_villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_villeActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_villeActionPerformed

    private void cb_restaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_restaurantActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_restaurantActionPerformed

    private void cb_loisirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_loisirsActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_loisirsActionPerformed

    private void cb_autorouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_autorouteActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_autorouteActionPerformed

    private void cb_nationaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nationalesActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_nationalesActionPerformed

    private void cb_departementaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_departementaleActionPerformed
        try{
            Canvas.clear();
            graphe = GrapheApp.getGraphe();
            Canvas.drawGraph(graphe);
        }
        catch(NullPointerException e){
            System.out.println("Pas de graphe");
        }
    }//GEN-LAST:event_cb_departementaleActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {
        jFrame1.pack();
        jFrame1.setVisible(true);
    }

    private void setNombres(){
        try{
            nbVille.setText("Nombre : " + GrapheApp.getGraphe().getNbVille());
            nbRestaurant.setText("Nombre : " +  GrapheApp.getGraphe().getNbRestaurant());
            nbLoisir.setText("Nombre : " +  GrapheApp.getGraphe().getNbLoisir());
            nbAutoroute.setText("Nombre : " +  GrapheApp.getGraphe().getNbAutoroutes());
            nbNationale.setText("Nombre : " +  GrapheApp.getGraphe().getNbNationales());
            nbDepartementale.setText("Nombre : " +  GrapheApp.getGraphe().getNbDepartementales());
        }
        catch(NullPointerException e){
            nbVille.setText("Nombre : 0");
            nbRestaurant.setText("Nombre : 0");
            nbLoisir.setText("Nombre : 0");
            nbAutoroute.setText("Nombre : 0");
            nbNationale.setText("Nombre : 0");
            nbDepartementale.setText("Nombre : 0");
        }
    }
    //getter cb
    public static JCheckBox getCb_ville() {
        return cb_ville;
    }

    public static JCheckBox getCb_restaurant() {
        return cb_restaurant;
    }

    public static JCheckBox getCb_autoroute() {
        return cb_autoroute;
    }

    public static JCheckBox getCb_nationale() {
        return cb_nationale;
    }

    public static JCheckBox getCb_departementale() {
        return cb_departementale;
    }

    public static JCheckBox getCb_loisirs() {
        return cb_loisirs;
    }

    public static GrapheDraw getCanvas() {
        return Canvas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static GrapheDraw Canvas;
    private static javax.swing.JCheckBox cb_loisirs;
    private static javax.swing.JCheckBox cb_restaurant;
    private static javax.swing.JCheckBox cb_ville;
    private static javax.swing.JCheckBox cb_departementale;
    private static javax.swing.JCheckBox cb_nationale;
    private static javax.swing.JCheckBox cb_autoroute;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_affichage;
    private javax.swing.JLabel nbVille;
    private javax.swing.JLabel nbRestaurant;
    private javax.swing.JLabel nbAutoroute;
    private javax.swing.JLabel nbNationale;
    private javax.swing.JLabel nbDepartementale;
    private javax.swing.JLabel nbLoisir;
    private javax.swing.JMenuItem openFile;
    private javax.swing.JPanel toolBarPan;
    // End of variables declaration//GEN-END:variables
}

class clickNode implements MouseListener, MouseMotionListener{
    private boolean clicked = false;
    private int node = -1;

    @Override
    public void mousePressed(MouseEvent e) {
        int x = e.getX();
        int y = e.getY();
        GrapheDraw Canvas = GUI.getCanvas();
        for(int i = 0; i < Canvas.getNbNodes(); i++){
            if(x >= Canvas.getNodes().get(i).getPosX() - 50 && x <= Canvas.getNodes().get(i).getPosX() + 50 && y >= Canvas.getNodes().get(i).getPosY() + 10 && y <= Canvas.getNodes().get(i).getPosY() + 50){
                node = i;
                clicked = true;
            }
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        int x = e.getX();
        int y = e.getY();
        GrapheDraw Canvas = GUI.getCanvas();
        if (clicked){
            Canvas.getNodes().get(node).setPosX(x);
            Canvas.getNodes().get(node).setPosY(y - 35);
            Canvas.repaint();
        }
        node = -1;
        clicked = false;
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }
    @Override
    public void mouseExited(MouseEvent e) {
    }
    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        int x = e.getX();
        int y = e.getY();
        GrapheDraw Canvas = GUI.getCanvas();
        for(int i = 0; i < Canvas.getNbNodes(); i++){
            if(x >= Canvas.getNodes().get(i).getPosX() - 50 && x <= Canvas.getNodes().get(i).getPosX() + 50 && y >= Canvas.getNodes().get(i).getPosY() + 10 && y <= Canvas.getNodes().get(i).getPosY() + 50){
                if(Canvas.getNodes().get(i).height < 75){
                    Canvas.getNodes().get(i).height = Canvas.getNodes().get(i).height + 5;
                }
                if (Canvas.getNodes().get(i).width < 100){
                    Canvas.getNodes().get(i).width = Canvas.getNodes().get(i).width + 2;
                }
                Canvas.repaint();
            }
            else{
                Canvas.getNodes().get(i).resetSize();
                Canvas.repaint();
            }
        }
    }

    @Override
    public void mouseDragged(MouseEvent e) {
    }
}
